<a href="https://colab.research.google.com/github/Margo-by/neural-networks/blob/main/4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Задание 1
import numpy as np

# Сигмоида
def nonlin(x, deriv=False):
    if deriv:
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

#входные и выходные данные подразумевают исключающее или
# набор входных данных
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

# выходные данные
y = np.array([[0, 1, 1, 0]]).T

# сделаем случайные числа более определенными
np.random.seed(1)

# инициализируем веса случайным образом со средним 0 в диапазоне(-1,1)
syn0 = 2 * np.random.random((2, 1)) - 1

for iter in range(10000):
    # прямое распространение
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))

    # насколько мы ошиблись?
    l1_error = y - l1

    # перемножим это с наклоном сигмоиды на основе значений в l1
    l1_delta = l1_error * nonlin(l1, True)  # !!! - производная сигмоидной функции nonlin
    # используется при вычислении l1_delta в процессе обратного распространения ошибки (backpropagation).

    # обновим веса
    """
    выполняет матричное умножение между транспонированной матрицей l0 и матрицей ошибок l1_delta.
    Результатом этого умножения будет матрица весовых обновлений,
    где каждый элемент представляет собой вклад конкретного признака в изменение веса.
    """
    syn0 += np.dot(l0.T, l1_delta)

print("Выходные данные после тренировки:")
print(l1)
print('Веса:')
print(syn0)


Выходные данные после тренировки:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Веса:
[[-3.19189120e-16]
 [ 1.52655666e-16]]


In [ ]:
#Задание 1
import numpy as np

# Сигмоида
def nonlin(x, deriv=False):
    if deriv:
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

#входные и выходные данные подразумевают что результат совпадает с первым столбцом
# набор входных данных
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

# выходные данные
y = np.array([[0, 0, 1, 1]]).T

# сделаем случайные числа более определенными
np.random.seed(1)

# инициализируем веса случайным образом со средним 0 в диапазоне(-1,1)
syn0 = 2 * np.random.random((2, 1)) - 1

for iter in range(10000):
    # прямое распространение
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))

    # насколько мы ошиблись?
    l1_error = y - l1

    # перемножим это с наклоном сигмоиды на основе значений в l1
    l1_delta = l1_error * nonlin(l1, True)  # !!! - производная сигмоидной функции nonlin
    # используется при вычислении l1_delta в процессе обратного распространения ошибки (backpropagation).

    # обновим веса
    """
    выполняет матричное умножение между транспонированной матрицей l0 и матрицей ошибок l1_delta.
    Результатом этого умножения будет матрица весовых обновлений,
    где каждый элемент представляет собой вклад конкретного признака в изменение веса.
    """
    syn0 += np.dot(l0.T, l1_delta)

print("Выходные данные после тренировки:")
print(l1)
print('Веса:')
print(syn0)


Выходные данные после тренировки:
[[0.5       ]
 [0.01253477]
 [0.99986896]
 [0.98978102]]
Веса:
[[ 8.93997576]
 [-4.36668704]]


не очень хорошие выходные реззультаты

*результат задания 2* получился довольно хороший за счёт появления скрытого слоя с 7,8 нейронами
Error:0.4994800947259584
l2:[[0.00510093]
 [0.99168975]
 [0.99126444]
 [0.0069945 ]]

в случае 1-6 нейронов плохой результат
Error:0.4995289647766772
l2:[[0.49553727]
 [0.49628491]
 [0.4987933 ]
 [0.49892142]]


In [ ]:
#Задание 2

import numpy as np

def nonlin(x, deriv=False):
    if deriv:
        return nonlin(x) * (1 - nonlin(x))
    return 1 / (1 + np.exp(-x))

X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

np.random.seed(1)

# случайно инициализируем веса, в среднем - 0, на скрытом слое 4 нейрона
syn0 = 2 * np.random.random((2,4)) - 1
syn1 = 2 * np.random.random((4,1)) - 1

for j in range(10000):
    # проходим вперёд по слоям 0, 1 и 2
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))

    # как сильно мы ошиблись относительно нужной величины?
    l2_error = y - l2

    if (j % 10000) == 0:
        print("Error:" + str(np.mean(np.abs(l2_error))))


    # в какую сторону нужно двигаться?
    # если мы были уверены в предсказании, то сильно менять его не надо
    l2_delta = l2_error * nonlin(l2, deriv=True)

    # как сильно значения l1 влияют на ошибки в l2?
    l1_error = l2_delta.dot(syn1.T)

    # в каком направлении нужно двигаться, чтобы прийти к l1?
    # если мы были уверены в предсказании, то сильно менять его не надо
    l1_delta = l1_error * nonlin(l1, deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
print("l2:" + str( l2))

Error:0.4995289647766772
l2:[[0.49553727]
 [0.49628491]
 [0.4987933 ]
 [0.49892142]]


в случае 2 скрытых слоёв результат получается хорошим при 4 и 2 нейронах на них соответственно
Error:0.5000826823194491
Error:0.49998310863771056
Error:0.003015131544639153
Error:0.0008530598886112963
Error:0.001191402410640795
Error:0.000531551146049807
l3:[[3.13671307e-04]
 [9.99902353e-01]
 [9.99824419e-01]
 [6.03064499e-05]]

In [20]:
#4 слоя
import numpy as np

def nonlin(x, deriv=False):
    if deriv:
        return nonlin(x) * (1 - nonlin(x))
    return 1 / (1 + np.exp(-x))

X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

np.random.seed(1)

# случайно инициализируем веса, в среднем - 0
syn0 = 2 * np.random.random((2,4)) - 1
syn1 = 2 * np.random.random((4,2)) - 1
syn2 = 2 * np.random.random((2,1)) - 1

for j in range(60000):
    # проходим вперёд по слоям 0, 1, 2 и 3
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))
    l3 = nonlin(np.dot(l2, syn2))

    # как сильно мы ошиблись относительно нужной величины?
    l3_error = y - l3

    if (j % 10000) == 0:
        print("Error:" + str(np.mean(np.abs(l3_error))))


    # в какую сторону нужно двигаться?
    # если мы были уверены в предсказании, то сильно менять его не надо
    l3_delta = l3_error * nonlin(l3, deriv=True)

    # как сильно значения l2 влияют на ошибки в l3?
    l2_error = l3_delta.dot(syn2.T)
    l2_delta = l2_error * nonlin(l2, deriv=True)

    # как сильно значения l1 влияют на ошибки в l2?
    l1_error = l2_delta.dot(syn1.T)
    l1_delta = l1_error * nonlin(l1, deriv=True)

    syn2 += l2.T.dot(l3_delta)
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
print("l3:" + str( l3))


Error:0.5000826823194491
Error:0.49998310863771056
Error:0.003015131544639153
Error:0.0008530598886112963
Error:0.001191402410640795
Error:0.000531551146049807
l3:[[3.13671307e-04]
 [9.99902353e-01]
 [9.99824419e-01]
 [6.03064499e-05]]
