<a href="https://colab.research.google.com/github/Margo-by/neural-networks/blob/main/4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Задание1
Построить прогноз курса доллара США на основе
курсов за 4 предшествующих дня на основе имеющихся у нас значений
курса за 13 дней начиная с 01.01.2019: https://www.nbrb.by/statistics/Rates/RatesDaily.asp.

In [ ]:
import numpy as np

# Исходные данные
data = np.array([
    [2.1598, 2.1598, 2.1701, 2.1788, 2.1727],
    [2.1598, 2.1701, 2.1788, 2.1727, 2.1727],
    [2.1701, 2.1788, 2.1727, 2.1727, 2.1727],
    [2.1788, 2.1727, 2.1727, 2.1727, 2.1727],
    [2.1727, 2.1727, 2.1727, 2.1727, 2.1590],
    [2.1727, 2.1727, 2.1727, 2.1590, 2.1569],
    [2.1727, 2.1727, 2.1590, 2.1569, 2.1532],
    [2.1727, 2.1590, 2.1569, 2.1532, 2.1503],
    [2.1590, 2.1569, 2.1532, 2.1503, 2.1503]
])

# Нормализация данных
max=np.max(data)
min=np.min(data)
normalized_data = (data - min) / (max - min)
print(normalized_data)
print(min)
print(max)
def orig(x):
    min=2.1503
    max=2.1788
    return x*(max-min)+min
print(orig(0.88125793))

[[0.33333333 0.33333333 0.69473684 1.         0.78596491]
 [0.33333333 0.69473684 1.         0.78596491 0.78596491]
 [0.69473684 1.         0.78596491 0.78596491 0.78596491]
 [1.         0.78596491 0.78596491 0.78596491 0.78596491]
 [0.78596491 0.78596491 0.78596491 0.78596491 0.30526316]
 [0.78596491 0.78596491 0.78596491 0.30526316 0.23157895]
 [0.78596491 0.78596491 0.30526316 0.23157895 0.10175439]
 [0.78596491 0.30526316 0.23157895 0.10175439 0.        ]
 [0.30526316 0.23157895 0.10175439 0.         0.        ]]
2.1503
2.1788
2.175415851005


In [ ]:
#Задание 1
import numpy as np

def nonlin(x, deriv=False):
    if deriv:
        return nonlin(x) * (1 - nonlin(x))
    return 1 / (1 + np.exp(-x))
def orig(x):
    min=2.1503
    max=2.1788
    return x*(max-min)+min

X = np.array([[0.33333333, 0.33333333, 0.69473684, 1.],
    [0.33333333, 0.69473684, 1., 0.78596491],
    [0.69473684, 1., 0.78596491, 0.78596491],
    [1., 0.78596491, 0.78596491, 0.78596491],
    [0.78596491, 0.78596491, 0.78596491, 0.78596491],
    [0.78596491, 0.78596491, 0.78596491, 0.30526316],
    [0.78596491, 0.78596491, 0.30526316, 0.23157895],
    [0.78596491, 0.30526316, 0.23157895, 0.10175439,],
    [0.30526316, 0.23157895, 0.10175439, 0.]
    ])


y = np.array([[0.78596491], [0.78596491], [0.78596491], [0.78596491], [0.30526316], [0.23157895], [0.10175439], [0], [0]])



np.random.seed(1)

# случайно инициализируем, на скрытом слое 16 нейрона
syn0 =  2*np.random.random((4,16)) - 1
syn1 =  2*np.random.random((16,1)) - 1

for j in range(100000):
    # проходим вперёд по слоям 0, 1 и 2
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))
    # как сильно мы ошиблись относительно нужной величины?
    l2_error = y - l2
    if (j == 99999) :
        print("Error:" + str(np.mean(np.abs(l2_error))))
        print("l2:" + str( l2))
        print("y:" + str( y))
    # в какую сторону нужно двигаться?
    # если мы были уверены в предсказании, то сильно менять его не надо
    l2_delta = l2_error * nonlin(l2, deriv=True)
    # как сильно значения l1 влияют на ошибки в l2?
    l1_error = l2_delta.dot(syn1.T)

    # в каком направлении нужно двигаться, чтобы прийти к l1?
    # если мы были уверены в предсказании, то сильно менять его не надо
    l1_delta = l1_error * nonlin(l1, deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
z= np.array([[2.1532,	2.1503,	2.1503,	2.1503]])
forecast=nonlin(np.dot(nonlin(np.dot(z, syn0)), syn1))
forecast=(orig(forecast))
print("z:" + str(z))
print("forecast:" + str(forecast))
real_z=2.1542
print("real_z:" + str(real_z))



Error:0.0002089015274925939
l2:[[7.85777994e-01]
 [7.86121098e-01]
 [7.86219041e-01]
 [7.85959429e-01]
 [3.05321926e-01]
 [2.31569362e-01]
 [1.01142551e-01]
 [2.63922122e-04]
 [3.33281861e-04]]
y:[[0.78596491]
 [0.78596491]
 [0.78596491]
 [0.78596491]
 [0.30526316]
 [0.23157895]
 [0.10175439]
 [0.        ]
 [0.        ]]
z:[[2.1532 2.1503 2.1503 2.1503]]
forecast:[[2.15609793]]
real_z:2.1542




```
# Выбран кодовый формат
```
Задание 2
'''
С помощью нейронной сети на основе анализа набора характеристик, непонятно как
влияющих на отнесение к классам, произвести классификацию транспортных средств по классам:
Легковой автомобиль; Пассажирский транспорт; Грузовой транспорт.

За основу взять следующие характеристики:

0) Большая снаряженная масса,

1) Большая мощность двигателя,

2) Большая пассажировместимость,

3) Большая грузоподъёмность.

Экспертная оценка характеристик даёт нам следующую таблицу нормализации:

                                          0        0.25       0.50      0.75       1

    -----------------------------------------------------------------------------------

    0) Большая масса автомобиля(т.)      ≤0.5     (0.5;1]    (1;2]     (2;5]      >5

    1) Большая мощность двигателя(л.с.)  ≤20      (20;50]    (50;100]  (100;200]  >200

    2) Большое пассажировместимость(чел) ≤2       (2;5]      (5;10]    (10;20]    >20

    3) Большая грузоподъёмность(т.)      ≤1       (2;2]      (2;3]     (2;4]      >4

    для обучения:
    примеры характеристик транспортных средств:

                   Масса(т.)   Двигатель(л.с.)  Пассажиров(чел.)  Грузоподъёмн.(т.)

----------------------------------------------------------------------------------

Ока                  0.645          33                 4                   0.34

Газель пасcaжир.     2.880         152                14                   1.5

Лада Калина          1.110          88                 5                   0.475

Камаз(3 оси)        10.400         260                 3                   6

Газель груз .        2.880         152                 3                   1.5

ПАЗ4234(пазик)       9.895         122                30                   6.2

ЗИЛ-5301(бычок)      3.695         136                 3                   3

УАЗ Патриот          2.170         116                 5                   0.6

ЛиАЗ-6213           27.895         278               150                  11

'''



In [ ]:
#Задание 2
import numpy as np
def nonlin(x, deriv=False):
    if deriv:
        return nonlin(x) * (1 - nonlin(x))
    return 1 / (1 + np.exp(-x))
# Создание массива данных на основе таблицы
data = np.array([
    [0.645, 33, 4, 0.34],        # Ока
    [2.880, 152, 14, 1.5],       # Газель пассажирская
    [1.110, 88, 5, 0.475],       # Лада Калина
    [10.400, 260, 3, 6],         # Камаз (3 оси)
    [2.880, 152, 3, 1.5],        # Газель грузовая
    [9.895, 122, 30, 6.2],       # ПАЗ4234 (пазик)
    [3.695, 136, 3, 3],          # ЗИЛ-5301 (бычок)
    [2.170, 116, 5, 0.6],        # УАЗ Патриот
    [27.895, 278, 150, 11]       # ЛиАЗ-6213
])
# Создаем массив выходных данных на основе предоставленной таблицы
output_data = np.array([
    [1, 0, 0],  # Ока
    [0, 1, 0],  # Газель пассажирская
    [1, 0, 0],  # Лада Калина
    [0, 0, 1],  # Камаз (3 оси)
    [0, 0, 1],  # Газель грузовая
    [0, 1, 0],  # ПАЗ4234 (пазик)
    [0, 0, 1],  # ЗИЛ-5301 (бычок)
    [1, 0, 0],  # УАЗ Патриот
    [0, 1, 0]   # ЛиАЗ-6213
])
print("Входные данные:")
print(data)

def normalize(parameter, value):
    normalization_table = {
        0: [(float('-inf'), 0.5), (0.5, 1), (1, 2), (2, 5), (5, float('inf'))],
        1: [(float('-inf'), 20), (20, 50), (50, 100), (100, 200), (200, float('inf'))],
        2: [(float('-inf'), 2), (2, 5), (5, 10), (10, 20), (20, float('inf'))],
        3: [(float('-inf'), 1), (1, 2), (2, 3), (3, 4), (4, float('inf'))]
    }

    for interval_index, interval in enumerate(normalization_table[parameter]):
        if interval[0] < value <= interval[1]:
            return interval_index * 0.25
    return None

# Применение нормализации к данным
normalized_data = np.zeros_like(data, dtype=float)  # Создаем пустой массив для нормализованных данных

for i in range(data.shape[1]):  # Проходим по столбцам данных
    for j in range(data.shape[0]):  # Проходим по строкам данных
        normalized_data[j, i] = normalize(i, data[j, i])  # Применяем нормализацию к каждому значению

print("Нормализованные данные:")
print(normalized_data)

print("Выходные данные:")
print(output_data)

np.random.seed(1)

# случайно инициализируем, на скрытом слое 16 нейрона
syn0 =  2*np.random.random((4,16)) - 1
syn1 =  2*np.random.random((16,3)) - 1

for j in range(500):
    # проходим вперёд по слоям 0, 1 и 2
    l0 =normalized_data
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))
    # как сильно мы ошиблись относительно нужной величины?
    l2_error = output_data - l2
    if (j %100==0) :
        print("Error:" + str(np.mean(np.abs(l2_error))))
    if (j ==499) :
        print("l2:" + str( l2))
    # в какую сторону нужно двигаться?
    # если мы были уверены в предсказании, то сильно менять его не надо
    l2_delta = l2_error * nonlin(l2, deriv=True)
    # как сильно значения l1 влияют на ошибки в l2?
    l1_error = l2_delta.dot(syn1.T)

    # в каком направлении нужно двигаться, чтобы прийти к l1?
    # если мы были уверены в предсказании, то сильно менять его не надо
    l1_delta = l1_error * nonlin(l1, deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

def classify_cars_with_confidence(l2):
    results = []
    for row in l2:
        # Вычисление суммы вероятностей в строке
        row_sum = np.sum(row)
        # Вычисление процентов для каждого класса
        confidences = [value / row_sum * 100 for value in row]
        # Форматирование результатов
        result_str = ", ".join([f"{conf:.2f}%" for conf in confidences])
        results.append(result_str)
    return results

# Вызов функции и вывод результатов
results = classify_cars_with_confidence(l2)
print("Результаты классификации с уверенностями(Легковой автомобиль; Пассажирский транспорт; Грузовой транспорт):")
for result in results:
    print(result)




Входные данные:
[[  0.645  33.      4.      0.34 ]
 [  2.88  152.     14.      1.5  ]
 [  1.11   88.      5.      0.475]
 [ 10.4   260.      3.      6.   ]
 [  2.88  152.      3.      1.5  ]
 [  9.895 122.     30.      6.2  ]
 [  3.695 136.      3.      3.   ]
 [  2.17  116.      5.      0.6  ]
 [ 27.895 278.    150.     11.   ]]
Нормализованные данные:
[[0.25 0.25 0.25 0.  ]
 [0.75 0.75 0.75 0.25]
 [0.5  0.5  0.25 0.  ]
 [1.   1.   0.25 1.  ]
 [0.75 0.75 0.25 0.25]
 [1.   0.75 1.   1.  ]
 [0.75 0.75 0.25 0.5 ]
 [0.75 0.75 0.25 0.  ]
 [1.   1.   1.   1.  ]]
Выходные данные:
[[1 0 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]]
Error:0.5601833821611413
Error:0.07857154709995633
Error:0.04830001104551992
Error:0.02922928090278974
Error:0.019070856960113878
l2:[[9.85366145e-01 3.87188904e-02 4.34633491e-06]
 [1.49865867e-02 9.73830740e-01 9.26410164e-05]
 [9.77277018e-01 7.36128340e-03 5.52028891e-04]
 [2.44909814e-04 5.98987816e-03 9.98163229e-01]
 [3.33059506

In [ ]:
z = np.array([
    [0.645, 33, 4, 0.34],        # Ока
    [2.880, 152, 14, 1.5],       # Газель пассажирская
    [1.110, 88, 5, 0.475],       # Лада Калина
    [10.400, 260, 3, 6],         # Камаз (3 оси)
    [2.880, 152, 3, 1.5],        # Газель грузовая
    [9.895, 122, 30, 6.2],       # ПАЗ4234 (пазик)
    [3.695, 136, 3, 3],          # ЗИЛ-5301 (бычок)
    [2.170, 116, 5, 0.6],        # УАЗ Патриот
    [27.895, 278, 150, 11]       # ЛиАЗ-6213
])
# Применение нормализации к данным
normalized_z = np.zeros_like(z, dtype=float)
for i in range(z.shape[1]):  # Проходим по столбцам данных
    for j in range(z.shape[0]):  # Проходим по строкам данных
        normalized_z[j, i] = normalize(i, z[j, i])  # Применяем нормализацию к каждому значению
forecast=nonlin(np.dot(  nonlin(np.dot(normalized_z, syn0)), syn1))
print("z:" + str(normalized_z))
print("forecast:" + str(forecast))
results = classify_cars_with_confidence(forecast)
print("Результаты классификации с уверенностями(Легковой автомобиль; Пассажирский транспорт; Грузовой транспорт):")
for result in results:
    print(result)



z:[[0.25 0.25 0.25 0.  ]
 [0.75 0.75 0.75 0.25]
 [0.5  0.5  0.25 0.  ]
 [1.   1.   0.25 1.  ]
 [0.75 0.75 0.25 0.25]
 [1.   0.75 1.   1.  ]
 [0.75 0.75 0.25 0.5 ]
 [0.75 0.75 0.25 0.  ]
 [1.   1.   1.   1.  ]]
forecast:[[9.85388992e-01 3.86854907e-02 4.32424380e-06]
 [1.49385593e-02 9.73825159e-01 9.28210443e-05]
 [9.77342166e-01 7.35451179e-03 5.50193831e-04]
 [2.44269218e-04 5.98687897e-03 9.98166680e-01]
 [3.32538302e-02 1.07335272e-02 9.19494726e-01]
 [6.66980454e-04 9.86981566e-01 4.16816777e-03]
 [1.00445294e-03 1.84350942e-02 9.91203382e-01]
 [9.56877439e-01 1.11214238e-03 5.82398812e-02]
 [6.14055417e-04 9.78804543e-01 9.60408974e-03]]
Результаты классификации с уверенностями(Легковой автомобиль; Пассажирский транспорт; Грузовой транспорт):
96.22%, 3.78%, 0.00%
1.51%, 98.48%, 0.01%
99.20%, 0.75%, 0.06%
0.02%, 0.60%, 99.38%
3.45%, 1.11%, 95.43%
0.07%, 99.51%, 0.42%
0.10%, 1.82%, 98.08%
94.16%, 0.11%, 5.73%
0.06%, 98.97%, 0.97%


In [ ]:
'''
  Масса(т.)   Двигатель(л.с.)   Пассажиров(чел.)   Грузоподъёмн.(т.)

-----------------------------------------------------------------------------------

Белаз              74,           1050                1                   90

БТР80              13.6           260               10                    3

Урал мото           0.3            40                3                    0.25

Повозка             0.2             1                4                    0.2

Велосипед           0.02            0.3              1                    0.1

Трамвай            18.4,          245              168                   12
'''




z = np.array([
    [74, 1050,1, 90],        # Белаз
    [13.6, 260, 10, 3],       # БТР80
    [0.3, 40, 3, 0.25],       # Урал мото
    [0.2, 1, 4, 0.2],         # Повозка
    [0.02, 0.3, 1,0.1],        # Велосипед
    [18.4, 245, 168, 12],       # Трамвай
])
# Применение нормализации к данным
normalized_z = np.zeros_like(z, dtype=float)
for i in range(z.shape[1]):  # Проходим по столбцам данных
    for j in range(z.shape[0]):  # Проходим по строкам данных
        normalized_z[j, i] = normalize(i, z[j, i])  # Применяем нормализацию к каждому значению
forecast=nonlin(np.dot(  nonlin(np.dot(normalized_z, syn0)), syn1))
print("z:" + str(normalized_z))
print("forecast:" + str(forecast))
results = classify_cars_with_confidence(forecast)
print("Результаты классификации с уверенностями(Легковой автомобиль; Пассажирский транспорт; Грузовой транспорт):")
for result in results:
    print(result)

z:[[1.   1.   0.   1.  ]
 [1.   1.   0.5  0.5 ]
 [0.   0.25 0.25 0.  ]
 [0.   0.   0.25 0.  ]
 [0.   0.   0.   0.  ]
 [1.   1.   1.   1.  ]]
forecast:[[4.96401026e-04 1.23733056e-04 9.99856547e-01]
 [7.52495933e-04 1.32823611e-01 9.62502050e-01]
 [9.95356239e-01 2.25547625e-02 6.61091042e-07]
 [9.96118076e-01 2.55672995e-02 2.31710534e-07]
 [9.99999944e-01 2.55623829e-10 4.15861764e-05]
 [6.14055417e-04 9.78804543e-01 9.60408974e-03]]
Результаты классификации с уверенностями(Легковой автомобиль; Пассажирский транспорт; Грузовой транспорт):
0.05%, 0.01%, 99.94%
0.07%, 12.12%, 87.81%
97.78%, 2.22%, 0.00%
97.50%, 2.50%, 0.00%
100.00%, 0.00%, 0.00%
0.06%, 98.97%, 0.97%


Результаты из примера

Белаз: Грузовая(100%), нельзя не согласиться
БТР80: Пассажирск.(27%), действительно пассажирский транспорт, но очень странный, да, потому и ответ неуверенный
Урал мото: Легковая(100%),Пассажирск.(12%), ну в целом ответ разумный, на легковую машину мотоцикл «Урал» похож больше, чем на автобус, но его способость везти аж 3 человек заставила нейросеть сомневаться
Повозка: Пассажирск.(52%), 1 лошадь, 200 кило телега и 4 человека на ней, неуверенно-пассажирский транспорт
Велосипед: не смогла определить что это … я бы тоже не смог
Трамвай: Пассажирск.(100%), тут никаких вопросов.

Задание 3.  (из темы 4.2, тест 4):

Построить и обучить нейронные сети с одним и двумя скрытыми слоями для распознавания прописных букв русского алфавита. В качестве входных данных использовать свои инициалы (ФИО).

In [ ]:
import numpy as np

def nonlin(x, deriv=False):
    if (deriv == True):
        return (x * (1 - x))

    return 1 / (1 + np.exp(-x))

'''
Б  1111100*1000000*1000000*1111100*1000010*1000010*1000010*1111100
Б2 1111110*1000000*1000000*1111100*1000010*1000010*1000010*1111100
M  1000001*1100011*1010101*1001001*1000001*1000001*1000001*1000001
M2 1000001*1100011*1010101*1001001*1000001*1000001*1000001*1000000
Д  0011000*0100100*0100100*0100100*0100100*0100100*1111110*1000010
Д2 0011000*0100100*0100100*0100100*0100100*0100100*1110110*1000010

'''
X = np.array([[1111100,1000000,000000,1111100,1000010,1000010,1000010,1111100],#b
              [1000001,1100011,1010101,1001001,1000001,1000001,1000001,1000001],#m
              [1111100, 1000010, 1000010, 1111100, 1000010, 1000010, 1000010, 1111100]])#d
y = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])
X = X
y = y

np.random.seed(1)

# случайно инициализируем веса, в среднем - 0
syn0 = 2 * np.random.random((8, 10)) - 1
syn1 = 2 * np.random.random((10, 3)) - 1

print(syn0)
print(syn1)

for j in range(60000):

    # проходим вперёд по слоям 0, 1 и 2
    l0 = X
    l11 = np.dot(l0, syn0)
    l1 = nonlin(l11)
    l22 = np.dot(l1, syn1)
    l2 = nonlin(l22)

    # как сильно мы ошиблись относительно нужной величины?
    l2_error = y - l2

    if (j % 5000) == 0:
        print ("Error:" + str(np.mean(np.abs(l2_error))))

    # в какую сторону нужно двигаться?
    # если мы были уверены в предсказании, то сильно менять его не надо
    l2_delta = (l2_error) * nonlin(l2, deriv=True)

    # как сильно значения l1 влияют на ошибки в l2?
    l1_error = np.dot(l2_delta, syn1.T)

    # в каком направлении нужно двигаться, чтобы прийти к l1?
    # если мы были уверены в предсказании, то сильно менять его не надо
    l1_delta = l1_error * nonlin(l1, deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

# прогноз

X = np.array([[11000, 10000, 100100, 1000010, 1111110, 1000010, 1000010, 1000001],
              [1111110, 1000000, 1000000, 1101100, 1000000, 1000000, 1000000, 1111110]])
y = np.array([[1, 0, 0]])

X = X
y = y

l0 = X
l11 = np.dot(l0, syn0)
l1 = nonlin(l11)
l22 = np.dot(l1, syn1)
l2 = nonlin(l22)

# как сильно мы ошиблись относительно нужной величины?
# l2_error = y - l2

# print('прогноз ош.:', l2_error)
print('знач. прогноза: ', l2)


[[-0.16595599  0.44064899 -0.99977125 -0.39533485 -0.70648822 -0.81532281
  -0.62747958 -0.30887855 -0.20646505  0.07763347]
 [-0.16161097  0.370439   -0.5910955   0.75623487 -0.94522481  0.34093502
  -0.1653904   0.11737966 -0.71922612 -0.60379702]
 [ 0.60148914  0.93652315 -0.37315164  0.38464523  0.7527783   0.78921333
  -0.82991158 -0.92189043 -0.66033916  0.75628501]
 [-0.80330633 -0.15778475  0.91577906  0.06633057  0.38375423 -0.36896874
   0.37300186  0.66925134 -0.96342345  0.50028863]
 [ 0.97772218  0.49633131 -0.43911202  0.57855866 -0.79354799 -0.10421295
   0.81719101 -0.4127717  -0.42444932 -0.73994286]
 [-0.96126608  0.35767107 -0.57674377 -0.46890668 -0.01685368 -0.89327491
   0.14823521 -0.70654285  0.17861107  0.39951672]
 [-0.79533114 -0.17188802  0.38880032 -0.17164146 -0.90009308  0.07179281
   0.32758929  0.02977822  0.88918951  0.17311008]
 [ 0.80680383 -0.72505059 -0.72144731  0.61478258 -0.20464633 -0.66929161
   0.85501716 -0.30446828  0.50162421  0.45199597]]

<ipython-input-43-94821b41a994>:7: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))


Error:0.22534313491952063
Error:0.22476493794993888
Error:0.22442144643036072
Error:0.22418754259081075
Error:0.22401514501924025
Error:0.22388131181282458
Error:0.2237735299707914
Error:0.22368431886115245
Error:0.22360889568548034
Error:0.22354404119090146
знач. прогноза:  [[0.9970982  0.00219228 0.0021918 ]
 [0.00205081 0.49999281 0.49999281]]


In [ ]:
import numpy as np

# Исходный массив
X = np.array([[1111100,1000000,000000,1111100,1000010,1000010,1000010,1111100],
              [1000001,1100011,1010101,1001001,1000001,1000001,1000001,1000001],
              [1111100, 1000010, 1000010, 1111100, 1000010, 1000010, 1000010, 1111100]])

# Создание пустого массива нужной размерности
X_reshaped = np.zeros((X.shape[0], 56), dtype=int)

# Преобразование каждого числа в строку, разделение на отдельные цифры и заполнение нового массива
for i in range(X.shape[0]):
    for j, num in enumerate(X[i]):
        digits = [int(digit) for digit in str(num)]
        X_reshaped[i, j*7:j*7+len(digits)] = digits

print(X_reshaped)
print(X_reshaped.shape)


[[1 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 1 0 0 0 0 1 0 1
  0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 1 1 1 0 0]
 [1 0 0 0 0 0 1 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 0 0 1 0 0 1 1 0 0 0 0 0 1 1
  0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 1]
 [1 1 1 1 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 0 0 1 0 1
  0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 1 1 1 0 0]]
(3, 56)


In [ ]:
import numpy as np

def nonlin(x, deriv=False):
    if (deriv == True):
        return (x * (1 - x))

    return 1 / (1 + np.exp(-x))

'''
Б  1111100*1000000*1000000*1111100*1000010*1000010*1000010*1111100
Б2 1111110*1000000*1000000*1111100*1000010*1000010*1000010*1111100
M  1000001*1100011*1010101*1001001*1000001*1000001*1000001*1000001
M2 1000001*1100011*1010101*1001001*1000001*1000001*1000001*1000000
Д  0011000*0100100*0100100*0100100*0100100*0100100*1111110*1000010
Д2 0011000*0100100*0100100*0100100*0100100*0100100*1110110*1000010

'''
X = X_reshaped
y = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

np.random.seed(1)

# случайно инициализируем веса, в среднем - 0
syn0 = 2 * np.random.random((56, 10)) - 1
syn1 = 2 * np.random.random((10, 3)) - 1

for j in range(60000):

    # проходим вперёд по слоям 0, 1 и 2
    l0 = X
    l11 = np.dot(l0, syn0)
    l1 = nonlin(l11)
    l22 = np.dot(l1, syn1)
    l2 = nonlin(l22)

    # как сильно мы ошиблись относительно нужной величины?
    l2_error = y - l2

    if (j % 5000) == 0:
        print ("Error:" + str(np.mean(np.abs(l2_error))))

    # в какую сторону нужно двигаться?
    # если мы были уверены в предсказании, то сильно менять его не надо
    l2_delta = (l2_error) * nonlin(l2, deriv=True)

    # как сильно значения l1 влияют на ошибки в l2?
    l1_error = np.dot(l2_delta, syn1.T)

    # в каком направлении нужно двигаться, чтобы прийти к l1?
    # если мы были уверены в предсказании, то сильно менять его не надо
    l1_delta = l1_error * nonlin(l1, deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

# прогноз

l0 = X
l11 = np.dot(l0, syn0)
l1 = nonlin(l11)
l22 = np.dot(l1, syn1)
l2 = nonlin(l22)
print('знач. прогноза: ', l2)


Error:0.5096288153096077
Error:0.006448870930953386
Error:0.004502145793040466
Error:0.003652121409464864
Error:0.0031493408808234186
Error:0.0028080236857085765
Error:0.0025570575623074434
Error:0.00236260892463185
Error:0.0022062661361502683
Error:0.002077042892716334
Error:0.001967926284042686
Error:0.001874202585245428
знач. прогноза:  [[0.99770687 0.00127248 0.00223457]
 [0.00138433 0.99829713 0.00142114]
 [0.00217267 0.00115893 0.99750697]]


Прогноз для искажённых букв на 1 символ

In [ ]:
import numpy as np
# Исходный массив
X = np.array([[1111100,1010000,000000,1111100,1000010,1000010,1000010,1111100],
              [1000001,1110011,1010101,1001001,1000001,1000001,1000001,1000001],
              [1111100, 1100010, 1000010, 1111100, 1000010, 1000010, 1000010, 1111100]])

# Создание пустого массива нужной размерности
X_reshaped = np.zeros((X.shape[0], 56), dtype=int)

# Преобразование каждого числа в строку, разделение на отдельные цифры и заполнение нового массива
for i in range(X.shape[0]):
    for j, num in enumerate(X[i]):
        digits = [int(digit) for digit in str(num)]
        X_reshaped[i, j*7:j*7+len(digits)] = digits
# прогноз
l0 = X_reshaped
l11 = np.dot(l0, syn0)
l1 = nonlin(l11)
l22 = np.dot(l1, syn1)
l2 = nonlin(l22)
print('знач. прогноза: ', l2)

знач. прогноза:  [[0.99790892 0.00116567 0.00271445]
 [0.00117103 0.99821511 0.00184344]
 [0.00155572 0.00138389 0.9971386 ]]


прогноз для искажённых на 5 символов букв

In [ ]:
import numpy as np
# Исходный массив
X = np.array([[1111111,1111111,111111,1111111,1111111,1111111,1111111,1111111],
              [1001101,1110011,1011101,1001001,1001001,1000001,1000001,1000001],
              [1101100, 1100110, 1100010, 1101100, 1111110, 1000010, 1000010, 1111100]])

# Создание пустого массива нужной размерности
X_reshaped = np.zeros((X.shape[0], 56), dtype=int)

# Преобразование каждого числа в строку, разделение на отдельные цифры и заполнение нового массива
for i in range(X.shape[0]):
    for j, num in enumerate(X[i]):
        digits = [int(digit) for digit in str(num)]
        X_reshaped[i, j*7:j*7+len(digits)] = digits
# прогноз
l0 = X_reshaped
l11 = np.dot(l0, syn0)
l1 = nonlin(l11)
l22 = np.dot(l1, syn1)
l2 = nonlin(l22)
print('знач. прогноза: ', l2)

знач. прогноза:  [[0.42786994 0.41923997 0.02821977]
 [0.00193912 0.99713907 0.00229107]
 [0.00362733 0.01069306 0.94959127]]
